
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef DEV_CAN_DRV_H
#define DEV_CAN_DRV_H

#include "dev_can.h"		/*include dev_can.h*/

#define DEV_CAN_PRINT		DBG_8195A

#endif // TESTMASTER_H
