
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef EWTCANANALYSIS_OBJDICT_H
#define EWTCANANALYSIS_OBJDICT_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 EwtCanAnalysis_valueRangeTest (UNS8 typeValue, void * value);
const indextable * EwtCanAnalysis_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data EwtCanAnalysis_Data;
extern UNS8 temperature;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS8 sn[5];		/* Mapped at index 0x2001, subindex 0x01 - 0x05 */
extern UNS8 button_Undefined1;		/* Mapped at index 0x2002, subindex 0x01 */
extern UNS16 button_Undefined22;		/* Mapped at index 0x2002, subindex 0x02 */
extern UNS8 button_Undefined333;		/* Mapped at index 0x2002, subindex 0x03 */
extern UNS8 button_Undefined4;		/* Mapped at index 0x2002, subindex 0x04 */
extern UNS32 button_Undefined5;		/* Mapped at index 0x2002, subindex 0x05 */
extern UNS8 button_Undefined6;		/* Mapped at index 0x2002, subindex 0x06 */
extern UNS8 button_Undefined77;		/* Mapped at index 0x2002, subindex 0x07 */

#endif // EWTCANANALYSIS_OBJDICT_H
