#ifndef _RTL8721D_USI_SSI_TEST_H_
#define _RTL8721D_USI_SSI_TEST_H_

/*SPI Test Case*/
typedef enum _USI_SSI_TEST_TYPE_
{
	USI_SSI_Master_LOOPBACK,
	USI_SSI_Master_TRX_POLL,
	USI_SSI_Master_TRX_INTERRUPT,
	USI_SSI_Master_TRX_DMA,
	USI_SSI_Slave_TRX_POLL,
	USI_SSI_Slave_TRX_INTERRUPT,
	USI_SSI_Slave_TRX_DMA,
	USI_SSI_Master_RX_ONLY,
	USI_SSI_Slave_RX_INTERRUPT,
	USI_SSI_MASTER_CS_SOFTWARE_NEW,
	USI_SSI_MASTER_LONG_RUN,
	USI_SSI_SLAVE_LONG_RUN,

	USI_SSI_TT_BASIC_IO,
	USI_SSI_TT_INTERRUPT,
	USI_SSI_TT_DMA_TO_TX,
	USI_SSI_TT_RX_TO_DMA,
	USI_SSI_TT_DMA_TX_TO_RX,
	USI_SSI_MASTER_RX_INTERRUPT,
	USI_SSI_MASTER_RX_TO_DMA,
	USI_SSI_MASTER_TX_INTERRUPT,
	USI_SSI_SLAVE_TX_INTERRUPT,
	USI_SSI_MASTER_RX_ONLY,
	USI_SSI_TT_TEST_ALL,
	USI_SSI_MASTER_CS_SOFTWARE,
	USI_SSI_OTHER_INTERFACE
} USI_SSI_TEST_TYPE, *PUSI_SSI_TEST_TYPE;

typedef enum _USI_SSI_TEST_SRC_DATA_MODE_
{
	USI_SSI_TEST_SRCDATA_SEQ,
	USI_SSI_TEST_SRCDATA_RND
} USI_SSI_TEST_SRC_DATA_MODE, *PUSI_SSI_TEST_SRC_DATA_MODE;

#endif
