
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef DEV_TEST_H
#define DEV_TEST_H

#include "rom_map.h"
#include <platform/platform_stdlib.h>
#include "platform_stdlib.h"
#include "basic_types.h"
#include "diag.h"
#include "rand.h"
#include "section_config.h"
#include "ameba_soc.h"
#include "rtl8721d_can_test.h"
#include "rtl8721d_can.h"
#include "FreeRTOSConfig.h"
#include "FreeRTOS.h"

#include "canfestival.h" 

#include "applicfg.h"
#include "config.h"
#include "dev_can.h"
#include "timerscfg.h"
#include "timer.h"

#include "dev_can_drv.h" 
#include "ObjDict.h"
#include "EwtCanAnalysis_objdict.h"

#include "dev_tim_drv.h"
#include "TestMaster.h"
#include "TestSlave.h"
#include "dev_master_test.h"
#include "dev_slave_test.h"

extern void canopen_drv_test_entry(u8  *argv[]);
extern u32 Strtoul(const u8 *nptr, u8 **endptr, u32 base);

#endif // TESTMASTER_H
