#ifndef WLANCONFIG_H
#define WLANCONFIG_H

#define PLATFORM_ECOS
#define CONFIG_LITTLE_ENDIAN
#define CONFIG_GSPI_HCI
//#define CONFIG_SDIO_HCI
#define CONFIG_80211N_HT
#define CONFIG_RECV_REORDERING_CTRL
#define RTW_NOTCH_FILTER	0
#define CONFIG_EMBEDDED_FWIMG	1
#define CONFIG_PHY_SETTING_WITH_ODM
#define HAL_MAC_ENABLE	1
#define HAL_BB_ENABLE	1
#define HAL_RF_ENABLE	1

//#define CONFIG_DEBUG
//#define CONFIG_DEBUG_RTL871X
//#define CONFIG_NO_FUNC_TRACE
//#define CONFIG_DEBUG_ALL
//#define CONFIG_WLAN_INTF_DBG
//#define CONFIG_SPI_WRITE_TRIGGER_LA
//#define CONFIG_SPI_READ_TRIGGER_LA
//#define CONFIG_USE_TRX_DEBUG_REG

#define CONFIG_XMIT_THREAD_MODE
#define CONFIG_RECV_THREAD_MODE
#define CONFIG_RECV_TASKLET_THREAD

/* DMEN optimized mode AES_IMPLEMENTATION_DMEM_OPTIMIZED comsume 10k less memory compare to 
   IMEM optimized mode AES_IMPLEMENTATION_IMEM_OPTIMIZED */
#define AES_IMPLEMENTATION_MODE AES_IMPLEMENTATION_IMEM_OPTIMIZED

#define USE_XMIT_EXTBUFF	1
#define SUPPORT_5G_CHANNEL	0
#define SUPPORT_FAKE_EFUSE	1
#define CONFIG_AUTO_RECONNECT

/* For WPA2 */
#define CONFIG_INCLUDE_WPA_PSK
#define DEFAULT_PASSPHRASE "1234567890"
#define CONFIG_WPA2_PREAUTH

#define CONFIG_RTL8188E
//#define RTL8188ES_SUPPORT	1
#define RTL8188E_SUPPORT	1
#define RTL8192C_SUPPORT	0
#define RTL8192CE_SUPPORT	0
#define RTL8192CU_SUPPORT	0
#define RTL8192D_SUPPORT	0
#define RTL8192DE_SUPPORT	0
#define RTL8192DU_SUPPORT	0
#define RTL8723A_SUPPORT	0
#define RTL8723AU_SUPPORT	0
#define RTL8723AS_SUPPORT	0
#define RTL8723_FPGA_VERIFICATION	0
#define RTL8188E_FOR_TEST_CHIP	0
#define RTL8188E_FPGA_TRUE_PHY_VERIFICATION	0
#define MP_DRIVER	0
#define DISABLE_BB_RF	0
#define DBG	0
#define RATE_ADAPTIVE_SUPPORT	1

#endif //WLANCONFIG_H
