name: Compile Examples

on:
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "Arduino_package/hardware/libraries/**"
      - "Arduino_package/hardware/cores/**"
      - "Arduino_package/hardware/variants/**"
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "Arduino_package/hardware/libraries/**"
      - "Arduino_package/hardware/cores/**"
      - "Arduino_package/hardware/variants/**"
  # workflow_dispatch event allows the workflow to be triggered manually
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  # repository_dispatch event allows the workflow to be triggered via the GitHub API
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

jobs:
  compile-examples:
    # same name as the fqbn (without the platform-name):
    name: Compile
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Arduino_package
            Arduino_zip_libraries

      - name: Compile examples 
        uses: arduino/compile-sketches@main
        with:
          fqbn: realtek:AmebaD:Ai-Thinker_BW16
          sketch-paths: |
            - Arduino_package/hardware/libraries/
          platforms: |
            # Install ambd_arduino via Boards Manager for the toolchain
            - source-url: https://github.com/ambiot/ambd_arduino/raw/master/Arduino_package/package_realtek_amebad_index.json
              name: realtek:AmebaD
            # Overwrite the ambd_arduino release version with the platform from the local path
            - source-path: Arduino_package/hardware/
              name: realtek:AmebaD
          libraries: |
            # The sketches typically don't have any external library dependencies, just some:
            - source-url: https://github.com/ambiot/ambd_arduino/raw/master/Arduino_zip_libraries/AmebaMotors.zip
            - source-url: https://github.com/ambiot/ambd_arduino/raw/master/Arduino_zip_libraries/AmebaEink.zip
            - name: "SparkFun ADXL313 Arduino Library"
          verbose: false
          enable-deltas-report: false
